---
#title: "Pre Processing"
output: 
  html_document:
    css: "../../www/custom.css"
---

<div class="bodyRmdContent">
## 5) Text Preprocessing
***
<p style="text-align: justify;">
To preprocess the text simply means to bring the text into a form that is predictable and analyzable for our task. For our project, a task here is a combination of approach and domain. For example, extracting top keywords with TF-IDF (approach) from Tweets (domain) is an example of our Task. Our dataset contains textual data. Thus, we performed pre-processing on our dataset before moving to exploratory data analysis.This is a very important step in Natural language processing and for building any machine learning model as it helps in minimizing the computational time and also produces better quality tokens which further helps in correct research. The objective was achieved by using R libraries like dplyr,tm  and tidyverse.
</p>
Following steps were performed in data pre-processing:<br>
<li>Removed Stop words from text</li>
<li>Removed punctuation, hyphen, numbers and roman numbers</li>
<li>Converted text to ASCII</li>
<li>Converted the text to lowercase</li>
<li>Performed stemming and tokenization</li>
```{r eval=FALSE}
text_preprocessing <- function(data) {
  processing<-data %>%
    
    {
      gsub('-', '', .)#removing hyphens
    } %>%
    
    {
      gsub('[[:punct:] ]+', ' ', .)#punctuation removal
    } %>%
    
    {
      gsub("\\b[IVXLCDM]+\\b", " ", .)#roman numbers removal
    } %>%
    
    tolower() %>% #changing to lowercase
    iconv(.,to="ASCII",sub="")%>%
    removeNumbers()%>%# removing numbers from data
    removeWords(words = stopwords(kind = "en")) #removing English dictionary stopwords
  return(processing)
}
```
</div>